language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
env:
  - RDM_QT_VERSION=57
  - RDM_QT_VERSION=561
  - RDM_QT_VERSION=551
  - RDM_QT_VERSION=542
before_install:
- sudo apt-key update
- sudo apt-get update
- sudo add-apt-repository --yes ppa:beineri/opt-qt${RDM_QT_VERSION}-trusty
- sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install qt${RDM_QT_VERSION:0:2}base libssl1.0.0 -y -qq
- sudo apt-get install gcc-4.9 g++-4.9 gdb lcov valgrind -y -qq
- sudo rm -f /usr/bin/gcov
- sudo rm -f /usr/bin/gcc
- sudo rm -f /usr/bin/g++
- sudo ln -s /usr/bin/gcov-4.9 /usr/bin/gcov
- sudo ln -s /usr/bin/gcc-4.9 /usr/bin/gcc
- sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++
- source /opt/qt${RDM_QT_VERSION:0:2}/bin/qt${RDM_QT_VERSION:0:2}-env.sh
- gem install coveralls-lcov
- qmake -v
- gcc --version
- gcov --version
script: 
  - if [ "$RDM_QT_VERSION" == "561" ]; then cd ./tests/unit_tests && ./run_tests; fi
  - qmake && make
after_success:
  - if [ "$RDM_QT_VERSION" == "561" ]; then coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info.filtered; fi
services:
  - redis-server
